var express = require('express')
var bodyParser = require('body-parser')
var urlencoded = bodyParser.urlencoded(({ extended: true }))
var querystring = require('querystring')
var coon = require('./routes/db')
var page = require('./routes/cart.js')
var app=express()
app.set('view engine','ejs')
app.use('/public',express.static('public'))
app.use(express.static('public/json'))
app.use('/',express.static('public/css'))
app.use('/cart',page)
app.use(urlencoded)
app.get('/',function(req,res){
    res.render('index',{})
})
app.listen(8000,function(){
    console.clear()
    console.log(new Date().toLocaleDateString())
})